In [2]:
from tdc.single_pred import Tox

data = Tox(name='hERG_Karim')
df_raw = data.get_data()
print(df_raw.shape)
df_raw.head()

Found local copy...
Loading...
Done!

(13445, 3)

   Drug_ID                                               Drug  Y
0        0                  Fc1ccc(-n2cc(NCCN3CCCCC3)nn2)cc1F  1
1        1  COc1cc(N2Cc3ccc(Sc4ccc(F)cc4)nc3C2=O)ccc1OCCN1...  0
2        2  CCOC(=O)[C@H]1CC[C@@H](N2CC(NC(=O)CNc3nn(C(N)=...  0
3        3  N[C@@H](Cn1c(=O)cnc2ccc(F)cc21)C1CCC(NCc2ccc3c...  0
4        4  O=C(NC1COc2cccc(-c3ccnc(CO)c3)c2C1)c1ccc(OCC(F...  0

In [3]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13445 entries, 0 to 13444
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Drug_ID  13445 non-null  int64
 1   Drug     13445 non-null  object
 2   Y        13445 non-null  int64
dtypes: int64(2), object(1)
memory usage: 315.2+ KB

In [13]:
df_raw['Y'].value_counts(normalize=True)

Y
0    0.500335
1    0.499665
Name: proportion, dtype: float64

In [15]:
df=df_raw.drop(columns=['Drug_ID']).copy()
df.head()

                                                Drug  Y
0                  Fc1ccc(-n2cc(NCCN3CCCCC3)nn2)cc1F  1
1  COc1cc(N2Cc3ccc(Sc4ccc(F)cc4)nc3C2=O)ccc1OCCN1...  0
2  CCOC(=O)[C@H]1CC[C@@H](N2CC(NC(=O)CNc3nn(C(N)=...  0
3  N[C@@H](Cn1c(=O)cnc2ccc(F)cc21)C1CCC(NCc2ccc3c...  0
4  O=C(NC1COc2cccc(-c3ccnc(CO)c3)c2C1)c1ccc(OCC(F...  0

The raw dataset had 3 columns: Drug_ID, Drug (molecular structure as a SMILES string) and Y, which is a target label. Target indicates whether the molecule blocks the hERG potassium channel (Y=1,IC50 < 10µM) or not (Y=0, IC50 >= 10 µM)  Drug_ID column was removes usefull information for prediction.

The dataset contains 13 445 molecules with no missing values and classes are well balanced.